# -*- mode: ruby -*-
# vi: set ft=ruby :

if Gem::Version.new(::Vagrant::VERSION) < Gem::Version.new('1.5')
  Vagrant.require_plugin('vagrant-hostmanager')
end

Vagrant.configure('2') do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box'

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.define :server1 do |server|
    server.vm.hostname = 'fry'
    server.vm.network :private_network, :ip => '10.0.5.2'
    server.hostmanager.aliases = %w(test-alias)
  end

  config.vm.define :server2 do |server|
    server.vm.hostname = 'bender'
    server.vm.network :private_network, :ip => '10.0.5.3'
  end
end
